// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc1gNxx_5xoRhRIDJE8zDsxxMkexwskZY',
    appId: '1:710744266024:web:5db274322b97a5f15eec1d',
    messagingSenderId: '710744266024',
    projectId: 'corona-virus-e391b',
    authDomain: 'corona-virus-e391b.firebaseapp.com',
    storageBucket: 'corona-virus-e391b.appspot.com',
    measurementId: 'G-ZLGFGQKN2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX-U5A8L66eFAC59yWj4Ol_wWvHnOKzHA',
    appId: '1:710744266024:android:a8491d64bacd1f305eec1d',
    messagingSenderId: '710744266024',
    projectId: 'corona-virus-e391b',
    storageBucket: 'corona-virus-e391b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYr7rbj48IfaFzp_lNXtKmbLjCCQ--Vi0',
    appId: '1:710744266024:ios:d7f99b4792e8a1475eec1d',
    messagingSenderId: '710744266024',
    projectId: 'corona-virus-e391b',
    storageBucket: 'corona-virus-e391b.appspot.com',
    iosClientId: '710744266024-6qtdg45d229sshrv2n8u2l6n6vv8uc1t.apps.googleusercontent.com',
    iosBundleId: 'com.dangol.coronaVirus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYr7rbj48IfaFzp_lNXtKmbLjCCQ--Vi0',
    appId: '1:710744266024:ios:ead3007215d6bd6f5eec1d',
    messagingSenderId: '710744266024',
    projectId: 'corona-virus-e391b',
    storageBucket: 'corona-virus-e391b.appspot.com',
    iosClientId: '710744266024-h8s67asbuikunbhfcq1p23f30r0tve1t.apps.googleusercontent.com',
    iosBundleId: 'com.dangol.coronaVirus.RunnerTests',
  );
}
